### ISSUE TITLE
如何获取博主同款tabby😉

### ISSUE THREAD

**Issue by a124997686** [moemoechu/tabby-background#2]
![image](https://github.com/moemoechu/tabby-background/assets/72393079/0d23fcc7-5538-4a42-b753-2a3e60814ad0)
这个字体，整个页面挺好看的怎么get💖

**Comment by moemoechu** [comment]
字体在这：https://github.com/lxgw/kose-font
logo是登录时调用neofetch
配色是tabby自带的ayu配色
