### ISSUE TITLE
background中的错误：[Object object]

### ISSUE THREAD

**Issue by marti844** [moemoechu/tabby-background#3]
安装时报错如下：
<img width="627" alt="截屏2024-06-14 01 10 14" src="https://github.com/moemoechu/tabby-background/assets/94387165/30e413bd-0ea7-44ce-ac65-5a53577b9e46">

**Comment by moemoechu** [comment]
一般是网络问题或者设置过npm镜像。

**Comment by zxbzxb180** [comment]
能否把项目下载放在插件目录直接用？

**Comment by moemoechu** [comment]
可以下载release中的zip包解压到tabby的插件目录的node_modules目录下
举个例子：
![image](https://github.com/user-attachments/assets/f20570ee-61d1-4a76-9a21-960996e374d9)

**Comment by zxbzxb180** [comment]
> 可以下载release中的zip包解压到tabby的插件目录的node_modules目录下 举个例子： ![image](https://private-user-images.githubusercontent.com/6707029/382992718-f20570ee-61d1-4a76-9a21-960996e374d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NzY2NDEsIm5iZiI6MTczMDc3NjM0MSwicGF0aCI6Ii82NzA3MDI5LzM4Mjk5MjcxOC1mMjA1NzBlZS02MWQxLTRhNzYtOWEyMS05NjA5OTZlMzc0ZDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDVUMDMxMjIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTg4NTE4YzZkNjlhNWE2OTdjOTc3YWQ4MTI0ZjRmOGIwZWUzYjkyMDQ3NmQyMGE5NDE4NGUwMjBjYjdiMmQ4NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.tOUtJsnDUEDR289pQ2_5FMSuF-2tqo9081MHYK0BoDE)

如果是mac捏？QAQ

**Comment by zxbzxb180** [comment]
plugins里没有node_modules，是否要手动创建？

**Comment by moemoechu** [comment]
> plugins里没有node_modules，是否要手动创建？

mac不清楚欸，已经不用mac了，可以用这个按钮打开插件目录看看，
![image](https://github.com/user-attachments/assets/98c9a905-0a0e-4a68-a2d7-c1aed0c614cc)

**Comment by zxbzxb180** [comment]
> > plugins里没有node_modules，是否要手动创建？
> 
> mac不清楚欸，已经不用mac了，可以用这个按钮打开插件目录看看， ![image](https://private-user-images.githubusercontent.com/6707029/382993921-98c9a905-0a0e-4a68-a2d7-c1aed0c614cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NzY5ODcsIm5iZiI6MTczMDc3NjY4NywicGF0aCI6Ii82NzA3MDI5LzM4Mjk5MzkyMS05OGM5YTkwNS0wYTBlLTRhNjgtYTJkNy1jMWFlZDBjNjE0Y2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDVUMDMxODA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDZjMWViYzk3OGE5MjUxOTUzYjdlZDkwOWJjNzBkYmEzMjE3MmEwYjYyNjYyNTRlZGZhY2UxNTg0NmIxYzFhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.zS2qi1tM3ZOBBdsuAOMm-5aPga_008xIYuLcCJ4arDI)

可能是我没装过插件，plugins里面是空的，我手动创建node_modules，把release丢进去重启就可以了，谢谢
![image](https://github.com/user-attachments/assets/7d4136a0-5f01-4571-b990-75cd690673b8)
